# Generated by Django 2.1.7 on 2019-03-05 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='监控点名称')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('dev_id', models.CharField(max_length=50, verbose_name='设备id')),
                ('status', models.BooleanField(default=True, verbose_name='设备状态')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='监控地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '云平台模型',
                'verbose_name_plural': '云平台模型',
            },
        ),
    ]
